// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
    production: false,
    url: "https://impsa.azurewebsites.net/api/"
};
